optimizer:
  target: torch.optim.Adam
  params:
    lr: 2.0e-5
    weight_decay : 1.0e-4

criterion:
  target: segmentation_models_pytorch.losses.FocalLoss
  params:
    mode: multiclass
    ignore_index: 3
    gamma: 3

early_stop_params:
  patience: 10
  min_delta: 1.0e-3

batch_size: 32
max_epochs: 500
limit_train_batches: 200
limit_val_batches: 200
train_workers: 14
val_workers: 14