optimizer:
  target: torch.optim.Adam
  params:
    lr: 2.0e-5
    weight_decay : 1.0e-3

criterion:
  target: segmentation_models_pytorch.losses.FocalLoss
  params:
    mode: multiclass
    ignore_index: 3
    gamma: 3

early_stop_params:
  patience: 10
  min_delta: 1.0e-3

max_epochs: 500
