name: thesis2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - console_shortcut
  - notebook
  - jupyterlab
  - gdal
variables:
  PROJ_LIB: /home/felferrari/anaconda3/envs/thesis2/share/proj
  HYDRA_FULL_ERROR: 1